<?php
use App\Http\Controllers\StudentLoginController;
use App\Http\Controllers\StudentWelcomeController;
use App\Http\Controllers\StudentDashboardController;
use App\Http\Controllers\StudentProfileController;
use App\Http\Controllers\StudentCourseController;
use App\Http\Controllers\StudentPointController;
use App\Http\Controllers\StudentPasswordController;
use App\Http\Controllers\StudentLogoutController;
use App\Http\Controllers\StudentReferController;
use App\Http\Controllers\StudentMediumController;
use Illuminate\Support\Facades\Route;
Route::get('/studentlogin',[StudentLoginController::class,'show'])->name('student.login');
Route::post('/studentlogin',[StudentLoginController::class,'login'])->name('student.login.submit');
Route::middleware('web')->group(function(){
Route::get('/student/welcome',[StudentWelcomeController::class,'index'])->name('student.welcome');
Route::get('/student/dashboard',[StudentDashboardController::class,'index'])->name('student.dashboard');
Route::get('/student/profile',[StudentProfileController::class,'index'])->name('student.profile');
Route::post('/student/profile',[StudentProfileController::class,'update'])->name('student.profile.update');
Route::post('/student/profile/active',[StudentProfileController::class,'active'])->name('student.profile.active');
Route::get('/student/medium',[StudentMediumController::class,'index'])->name('student.medium');
Route::post('/student/medium',[StudentMediumController::class,'update'])->name('student.medium.update');
Route::get('/student/refer',[StudentReferController::class,'index'])->name('student.refer');
Route::post('/student/refer/list',[StudentReferController::class,'list'])->name('student.refer.list');
Route::post('/student/refer/updatewhatsappp',[StudentReferController::class,'updateWhatsapp'])->name('student.refer.whatsapp');
Route::get('/student/course',[StudentCourseController::class,'index'])->name('student.course');
Route::get('/student/course/view',[StudentCourseController::class,'view'])->name('student.course.view');
Route::get('/student/course/sessionview',[StudentCourseController::class,'sessionView'])->name('student.course.session');
Route::post('/student/course/addrequest',[StudentCourseController::class,'addRequest'])->name('student.course.addrequest');
Route::post('/student/course/uploadrequest',[StudentCourseController::class,'uploadRequest'])->name('student.course.uploadrequest');
Route::get('/student/passbook',[StudentPointController::class,'passbook'])->name('student.passbook');
Route::post('/student/passbook/list',[StudentPointController::class,'passbookList'])->name('student.passbook.list');
Route::get('/student/withdrawal',[StudentPointController::class,'withdrawal'])->name('student.withdrawal');
Route::post('/student/withdrawal/list',[StudentPointController::class,'withdrawalList'])->name('student.withdrawal.list');
Route::post('/student/withdrawal/addrequest',[StudentPointController::class,'addWithdrawal'])->name('student.withdrawal.add');
Route::post('/student/point/joinrequest',[StudentPointController::class,'joinRequest'])->name('student.point.join');
Route::get('/student/password',[StudentPasswordController::class,'edit'])->name('student.password');
Route::post('/student/password',[StudentPasswordController::class,'update'])->name('student.password.update');
Route::get('/student/logout',StudentLogoutController::class)->name('student.logout');
Route::view('/block','student.block')->name('student.block');
});