use App\Http\Controllers\AdminLoginController;
use App\Http\Controllers\AdminDashboardController;
<?php
use App\Http\Controllers\StudentLoginController;
use App\Http\Controllers\StudentWelcomeController;
use App\Http\Controllers\StudentDashboardController;
use App\Http\Controllers\StudentProfileController;
use App\Http\Controllers\StudentCourseController;
use App\Http\Controllers\StudentPointController;
use App\Http\Controllers\StudentPasswordController;
use App\Http\Controllers\StudentLogoutController;
use App\Http\Controllers\StudentReferController;
use App\Http\Controllers\StudentMediumController;
use App\Http\Controllers\StudentSellPointController;
use App\Http\Controllers\StudentJoinPointController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CoursesController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\ForgotController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CreatorZoneController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PrivacyController;
use App\Http\Controllers\TermsConditionsController;
Route::get('/',[HomeController::class,'index'])->name('home');
Route::get('/about',[AboutController::class,'index'])->name('about');
Route::get('/privacy',[PrivacyController::class,'index'])->name('privacy');
Route::get('/terms-conditions',[TermsConditionsController::class,'index'])->name('terms');
Route::get('/contact',[ContactController::class,'index'])->name('contact');
Route::get('/creator-zone',[CreatorZoneController::class,'index'])->name('creator.zone');
Route::post('/contact',[ContactController::class,'send'])->name('contact.send');
Route::get('/courses',[CoursesController::class,'index'])->name('courses');
Route::get('/register',[RegisterController::class,'index'])->name('register');
Route::post('/register',[RegisterController::class,'store'])->name('register.store');
Route::get('/forgot',[ForgotController::class,'index'])->name('forgot');
Route::post('/forgot',[ForgotController::class,'send'])->name('forgot.send');
Route::get('/forgot/resetpassword/token/{token}',[ForgotController::class,'resetForm'])->name('forgot.reset');
Route::post('/forgot/resetpassword/token/{token}',[ForgotController::class,'reset'])->name('forgot.reset.update');
Route::get('/studentlogin',[StudentLoginController::class,'show'])->name('student.login');
Route::post('/studentlogin',[StudentLoginController::class,'login'])->name('student.login.submit');
Route::middleware('web')->group(function(){
Route::get('/student/welcome',[StudentWelcomeController::class,'index'])->name('student.welcome');
Route::get('/student/dashboard',[StudentDashboardController::class,'index'])->name('student.dashboard');
Route::get('/student/profile',[StudentProfileController::class,'index'])->name('student.profile');
Route::post('/student/profile',[StudentProfileController::class,'update'])->name('student.profile.update');
Route::post('/student/profile/active',[StudentProfileController::class,'active'])->name('student.profile.active');
Route::get('/student/medium',[StudentMediumController::class,'index'])->name('student.medium');
Route::post('/student/medium',[StudentMediumController::class,'update'])->name('student.medium.update');
Route::get('/student/joinpoint',[StudentJoinPointController::class,'index'])->name('student.joinpoint');
Route::get('/student/refer',[StudentReferController::class,'index'])->name('student.refer');
Route::post('/student/refer/list',[StudentReferController::class,'list'])->name('student.refer.list');
Route::post('/student/refer/updatewhatsappp',[StudentReferController::class,'updateWhatsapp'])->name('student.refer.whatsapp');
Route::get('/student/course',[StudentCourseController::class,'index'])->name('student.course');
Route::get('/student/ourcourse',[StudentCourseController::class,'index'])->name('student.ourcourse');
Route::get('/student/course/view',[StudentCourseController::class,'view'])->name('student.course.view');
Route::get('/student/course/sessionview',[StudentCourseController::class,'sessionView'])->name('student.course.session');
Route::post('/student/course/addrequest',[StudentCourseController::class,'addRequest'])->name('student.course.addrequest');
Route::post('/student/course/uploadrequest',[StudentCourseController::class,'uploadRequest'])->name('student.course.uploadrequest');
Route::get('/student/passbook',[StudentPointController::class,'passbook'])->name('student.passbook');
Route::post('/student/passbook/list',[StudentPointController::class,'passbookList'])->name('student.passbook.list');
Route::get('/student/withdrawal',[StudentPointController::class,'withdrawal'])->name('student.withdrawal');
Route::post('/student/withdrawal/list',[StudentPointController::class,'withdrawalList'])->name('student.withdrawal.list');
Route::post('/student/withdrawal/addrequest',[StudentPointController::class,'addWithdrawal'])->name('student.withdrawal.add');
Route::post('/student/point/joinrequest',[StudentPointController::class,'joinRequest'])->name('student.point.join');
Route::get('/student/password',[StudentPasswordController::class,'edit'])->name('student.password');
Route::post('/student/password',[StudentPasswordController::class,'update'])->name('student.password.update');
Route::get('/student/logout',StudentLogoutController::class)->name('student.logout');
Route::view('/block','student.block')->name('student.block');
});
Route::get('/adminlogin', [AdminLoginController::class, 'show'])->name('admin.login');
Route::post('/adminlogin', [AdminLoginController::class, 'login'])->name('admin.login.submit');
Route::post('/adminlogout', [AdminLoginController::class, 'logout'])->name('admin.logout');
Route::get('/admin', [AdminDashboardController::class, 'index'])->name('admin.dashboard');
