<?php
namespace App\Http\Controllers;
use App\Models\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
class AdminStudentController extends Controller {
 private function guard(Request $r):void{abort_unless($r->session()->has('admin_user_id')&&(int)$r->session()->get('admin_user_group_id')===1,403);}
 public function index(Request $r){$this->guard($r);$q=Student::query()->leftJoin('bh_student as ref','ref.id','=','bh_student.refer_id')->leftJoin('bh_user as trainer','trainer.user_id','=','bh_student.link_user_id')->leftJoin('bh_user_extra as te','te.user_id','=','trainer.user_id')->where('bh_student.student_delete_status',0)->where('bh_student.student_status',(int)$r->input('status',1))->select('bh_student.*','ref.student_name as refer_name','ref.student_no as refer_no','trainer.firstname as trainer_firstname','trainer.lastname as trainer_lastname','te.user_no as trainer_no');if($r->filled('search')){$s=$r->search;$q->where(fn($w)=>$w->where('bh_student.student_name','like',"%$s%")->orWhere('bh_student.student_no','like',"%$s%")->orWhere('bh_student.student_phone','like',"%$s%")->orWhere('bh_student.student_whatsapp','like',"%$s%")->orWhere('bh_student.student_email','like',"%$s%")->orWhere('bh_student.student_language','like',"%$s%"));}if($r->filled('student_no'))$q->where('bh_student.student_no',$r->student_no);if($r->filled('refer_no'))$q->where('ref.student_no',$r->refer_no);return view('admin.students.index',['students'=>$q->orderByDesc('bh_student.id')->paginate(25)->withQueryString(),'status'=>(int)$r->input('status',1)]);}
 public function edit(Request $r,int $student){$this->guard($r);$s=Student::findOrFail($student);abort_if((int)$s->student_delete_status===1,404);return view('admin.students.form',['student'=>$s,'trainers'=>DB::table('bh_user')->join('bh_user_extra','bh_user_extra.user_id','=','bh_user.user_id')->where('bh_user.user_group_id',11)->where('bh_user.status',1)->select('bh_user.user_id','bh_user.firstname','bh_user.lastname','bh_user_extra.user_no')->orderBy('bh_user.firstname')->get(),'mediums'=>DB::table('bh_student_payment_medium')->where('student_id',$student)->get()]);}
 public function update(Request $r,int $student){$this->guard($r);$s=Student::findOrFail($student);$d=$r->validate(['student_name'=>['required','string','max:100'],'student_phone'=>['required','string','max:50'],'student_whatsapp'=>['required','string','max:50'],'student_gender'=>['nullable','string','max:20'],'student_language'=>['nullable','string','max:50'],'student_country'=>['nullable','string','max:80'],'student_status'=>['required','in:0,1,2'],'refer_id'=>['nullable','integer'],'link_user_id'=>['nullable','integer'],'password'=>['nullable','string','min:8','confirmed']]);if(!empty($d['password']))$d['password']=Hash::make($d['password']);else unset($d['password']);$s->update($d);if($r->has('payment_medium'))DB::transaction(function()use($r,$student){DB::table('bh_student_payment_medium')->where('student_id',$student)->delete();foreach((array)$r->input('payment_medium',[]) as $m){if(trim($m['medium_name']??'')===''||trim($m['medium_code']??'')==='')continue;DB::table('bh_student_payment_medium')->insert(['student_id'=>$student,'medium_name'=>$m['medium_name'],'medium_code'=>$m['medium_code'],'medium_status'=>(int)($m['medium_status']??0)]);}});return redirect()->route('admin.students.index')->with('success','Student updated successfully.');}
 public function activate(Request $r,int $student){$this->guard($r);return DB::transaction(function()use($r,$student){$s=Student::query()->lockForUpdate()->findOrFail($student);abort_if((int)$s->student_delete_status===1||in_array((int)$s->student_status,[1,2],true),422);$referId=(int)($s->refer_id??0);$ref= $referId?Student::find($referId):null;$trainerId=(int)($ref->link_user_id??0);$tlId=$trainerId?(int)(DB::table('bh_user_extra')->where('user_id',$trainerId)->value('link_user_id')??0):0;$stlId=$tlId?(int)(DB::table('bh_user_extra')->where('user_id',$tlId)->value('link_user_id')??0):0;if($referId)$this->managePoint($referId,'Refer Student Activated','Point earn for activated refer ID '.$s->student_no.' Name '.$s->student_name,(float)$this->setting('config_refer_activated_point'),0,'Credit');$this->managePoint($student,'Student Cashback Point','Cashback Point From Admin',(float)$this->setting('config_cashback_point'),0,'Credit');$teamLeaderNo=$this->setting('config_team_leader_no');$teamLeaderId=(int)(DB::table('bh_user')->where('username',$teamLeaderNo)->value('user_id')??151);$now=now();$s->update(['link_user_id'=>$trainerId,'activated_at'=>$now,'link_user_at'=>$now,'student_status'=>1,'activated_by'=>$r->session()->get('admin_user_id')]);DB::table('bh_student_active_history')->insert(['student_id'=>$student,'refer_student_id'=>$referId,'refer_student_trainer_id'=>$trainerId,'refer_student_teamleader_id'=>$tlId,'refer_student_seniorteamleader_id'=>$stlId,'user_id'=>0,'team_leader_id'=>$teamLeaderId,'counsellor_id'=>(int)(DB::table('bh_student_to_counsellor')->where('student_id',$student)->value('user_id')??0),'added_on'=>$now]);return back()->with('success','Student activated successfully.');});}
 private function setting(string $key,$default=0){return DB::table('bh_setting')->where('key',$key)->value('value')??$default;}
 private function managePoint(int $id,string $reason,string $description,float $credit,float $debit,string $type):void{$balance=(float)(DB::table('bh_student_passbook')->where('student_id',$id)->orderByDesc('id')->value('balance_point')??0);$balance=$type==='Credit'?$balance+$credit:$balance-$debit;DB::table('bh_student_passbook')->insert(['student_id'=>$id,'reason'=>$reason,'description'=>$description,'credit_point'=>$credit,'debit_point'=>$debit,'balance_point'=>$balance,'type'=>$type,'created_at'=>now()]);Student::query()->whereKey($id)->update(['student_point'=>$balance,'updated_at'=>now()]);}
 public function joinApprove(Request $r,int $student){$this->guard($r);$s=Student::findOrFail($student);$s->admin_approve=1;$s->save();return back()->with('success','Join point approval completed.');}
 public function sendJoiningPoint(Request $r,int $student){$this->guard($r);$updated=DB::table('bh_student')->where('id',$student)->where('whatsapp_join',1)->where('telegram_join',1)->where('admin_approve',1)->where('is_point_requested',1)->update(['is_point_send'=>1]);abort_if(!$updated,422,'Joining point conditions are not complete.');return back()->with('success','Student joining point marked as sent.');}
 public function block(Request $r,int $student){$this->guard($r);$s=Student::findOrFail($student);abort_if((int)$s->student_status!==1,422);$s->student_status=2;$s->save();return back()->with('success','Student blocked successfully.');}
}