<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class AdminSessionController extends Controller{
 private function guard(Request $r):void{abort_unless($r->session()->has('admin_user_id')&&(int)$r->session()->get('admin_user_group_id')===1,403);}
 private function teachers(){return DB::table('bh_user')->where('status',1)->where('user_group_id',14)->orderBy('firstname')->get(['user_id','firstname','lastname']);}
 public function index(Request $r){$this->guard($r);$q=DB::table('bh_course_to_session as s')->join('bh_course as c','c.course_id','=','s.course_id')->leftJoin('bh_user as u','u.user_id','=','s.session_teacher_id')->where('s.delete_status',0)->select('s.*','c.course_name',DB::raw("TRIM(CONCAT(COALESCE(u.firstname,''),' ',COALESCE(u.lastname,''))) as teacher_name"));if($r->filled('course_id'))$q->where('s.course_id',$r->course_id);if($r->filled('teacher_id'))$q->where('s.session_teacher_id',$r->teacher_id);if($r->filled('from'))$q->whereDate('s.session_date','>=',$r->from);if($r->filled('to'))$q->whereDate('s.session_date','<=',$r->to);$sessions=$q->orderByDesc('s.session_id')->paginate(25)->withQueryString();$courses=DB::table('bh_course')->where('course_delete_status',0)->orderBy('course_name')->get(['course_id','course_name','no_of_classes','per_session_point']);return view('admin.sessions.index',compact('sessions','courses'))->with('teachers',$this->teachers());}
 public function create(Request $r){$this->guard($r);$courses=DB::table('bh_course')->where('course_delete_status',0)->where('course_status',1)->orderBy('course_name')->get(['course_id','course_name','no_of_classes','per_session_point']);return view('admin.sessions.form',['session'=>null,'courses'=>$courses,'teachers'=>$this->teachers()]);}
 public function store(Request $r){$this->guard($r);$d=$this->validateData($r);$point=DB::table('bh_course')->where('course_id',$d['course_id'])->value('per_session_point');foreach($d['session_no'] as $no){DB::table('bh_course_to_session')->insert(['course_id'=>$d['course_id'],'session_type'=>$d['session_type'],'session_date'=>$d['session_date'],'session_time'=>$d['session_time'],'session_teacher_id'=>$d['session_teacher_id'],'session_point'=>$point,'session_no'=>$no,'meeting_link'=>$d['meeting_link'],'delete_status'=>0,'session_created_at'=>now(),'session_updated_at'=>now(),'session_created_by'=>$r->session()->get('admin_user_id'),'session_updated_by'=>$r->session()->get('admin_user_id')]);}return redirect()->route('admin.sessions.index')->with('success','Session created successfully.');}
 public function edit(Request $r,int $session){$this->guard($r);$s=DB::table('bh_course_to_session')->where('session_id',$session)->where('delete_status',0)->first();abort_unless($s,404);$courses=DB::table('bh_course')->where('course_delete_status',0)->orderBy('course_name')->get(['course_id','course_name','no_of_classes','per_session_point']);return view('admin.sessions.form',['session'=>$s,'courses'=>$courses,'teachers'=>$this->teachers()]);}
 public function update(Request $r,int $session){$this->guard($r);abort_unless(DB::table('bh_course_to_session')->where('session_id',$session)->where('delete_status',0)->exists(),404);$d=$this->validateData($r,true);$point=DB::table('bh_course')->where('course_id',$d['course_id'])->value('per_session_point');DB::table('bh_course_to_session')->where('session_id',$session)->update(['course_id'=>$d['course_id'],'session_type'=>$d['session_type'],'session_date'=>$d['session_date'],'session_time'=>$d['session_time'],'session_teacher_id'=>$d['session_teacher_id'],'session_point'=>$point,'session_no'=>$d['session_no'][0],'meeting_link'=>$d['meeting_link'],'session_updated_at'=>now(),'session_updated_by'=>$r->session()->get('admin_user_id')]);return redirect()->route('admin.sessions.index')->with('success','Session updated successfully.');}
 private function validateData(Request $r,bool $edit=false){$d=$r->validate(['session_type'=>['required','in:Class,Backup'],'course_id'=>['required','integer','exists:bh_course,course_id'],'session_no'=>['required','array','min:1'],'session_no.*'=>['integer','min:1'],'session_teacher_id'=>['required','integer','exists:bh_user,user_id'],'meeting_link'=>['required','string','max:1000'],'session_date'=>['required','date'],'session_time'=>['required','string','max:20']]);abort_unless(DB::table('bh_user')->where('user_id',$d['session_teacher_id'])->where('status',1)->where('user_group_id',14)->exists(),422,'Invalid teacher.');abort_if(DB::table('bh_course_to_session')->where('meeting_link',$d['meeting_link'])->when($edit,function($q)use($r){$q->where('session_id','<>',(int)$r->route('session'));})->exists(),422,'Meeting link already exists.');return $d;}
 public function submissions(Request $r,int $session){$this->guard($r);$s=DB::table('bh_course_to_session as cs')->join('bh_course as c','c.course_id','=','cs.course_id')->where('cs.session_id',$session)->where('cs.delete_status',0)->select('cs.*','c.course_name')->first();abort_unless($s,404);$items=DB::table('bh_student_to_course_session as x')->join('bh_student as st','st.id','=','x.student_id')->where('x.session_id',$session)->select('x.*','st.student_name','st.student_no')->orderByDesc('x.id')->paginate(50)->withQueryString();return view('admin.sessions.submissions',compact('s','items'));}
 public function approve(Request $r,int $submission){$this->guard($r);$x=DB::table('bh_student_to_course_session')->where('id',$submission)->first();abort_unless($x,404);DB::table('bh_student_to_course_session')->where('id',$submission)->update(['point_status'=>1]);return back()->with('success','Submission approved.');}
 public function wrong(Request $r,int $submission){$this->guard($r);$x=DB::table('bh_student_to_course_session')->where('id',$submission)->first();abort_unless($x,404);DB::table('bh_student_to_course_session')->where('id',$submission)->update(['work_status'=>0]);return back()->with('success','Submission marked wrong.');}
}