<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class AdminFinanceController extends Controller {
 private function guard(Request $r):void{abort_unless($r->session()->has('admin_user_id')&&(int)$r->session()->get('admin_user_group_id')===1,403);}
 public function passbook(Request $r){$this->guard($r);$q=DB::table('bh_student_passbook as p')->join('bh_student as s','s.id','=','p.student_id')->select('p.*','s.student_no','s.student_name')->where('s.student_delete_status',0);if($r->filled('student_no'))$q->where('s.student_no',$r->student_no);if($r->filled('type'))$q->where('p.type',$r->type);if($r->filled('reason'))$q->where('p.reason','like','%'.$r->reason.'%');if($r->filled('from'))$q->whereDate('p.created_at','>=',$r->from);if($r->filled('to'))$q->whereDate('p.created_at','<=',$r->to);return view('admin.finance.passbook',['items'=>$q->orderByDesc('p.id')->paginate(30)->withQueryString()]);}
 public function payments(Request $r){$this->guard($r);$q=DB::table('bh_student_payment_history as p')->join('bh_student as s','s.id','=','p.student_id')->join('bh_student_withdrawal_request as w','w.id','=','p.withdrawal_request_id')->leftJoin('bh_student_payment_medium as m','m.id','=','p.payment_medium_id')->where('s.student_delete_status',0)->select('p.*','s.student_no','s.student_name','w.withdrawal_point','m.medium_name','m.medium_code');if($r->filled('student_no'))$q->where('s.student_no',$r->student_no);if($r->filled('transaction'))$q->where('p.transaction_id','like','%'.$r->transaction.'%');if($r->filled('from'))$q->whereDate('p.payment_date','>=',$r->from);if($r->filled('to'))$q->whereDate('p.payment_date','<=',$r->to);return view('admin.finance.payments',['items'=>$q->orderByDesc('p.id')->paginate(30)->withQueryString()]);}
 public function withdrawals(Request $r){$this->guard($r);$q=DB::table('bh_student_withdrawal_request as w')->join('bh_student as s','s.id','=','w.student_id')->where('s.student_delete_status',0)->select('w.*','s.student_no','s.student_name','s.student_whatsapp');if($r->filled('student_no'))$q->where('s.student_no',$r->student_no);if($r->filled('status'))$q->where('w.approve_status',$r->status);if($r->filled('from'))$q->whereDate('w.requested_at','>=',$r->from);if($r->filled('to'))$q->whereDate('w.requested_at','<=',$r->to);return view('admin.finance.withdrawals',['items'=>$q->orderByDesc('w.id')->paginate(30)->withQueryString()]);}
}