<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class AdminPointBuySellController extends Controller {
 private function guard(Request $r):void{abort_unless($r->session()->has('admin_user_id')&&(int)$r->session()->get('admin_user_group_id')===1,403);}
 private function users(){return DB::table('bh_user as u')->leftJoin('bh_user_extra as e','e.user_id','=','u.user_id')->where('u.user_group_id',17)->select('u.user_id','u.username','u.firstname','u.lastname','e.user_no','e.buy_status','e.sell_status')->orderBy('u.user_id','desc');}
 public function index(Request $r){$this->guard($r);$users=$this->users()->paginate(30)->withQueryString();return view('admin.pointbuysell.index',compact('users'));}
 public function wallet(Request $r,int $user){$this->guard($r);$u=$this->users()->where('u.user_id',$user)->firstOrFail();$buy=$this->summary('point_buy',$user);$sell=$this->summary('point_sell',$user);$buys=DB::table('point_buy')->leftJoin('bh_student as s','s.id','=','point_buy.student_id')->where('point_buy.user_id',$user)->select('point_buy.*','s.student_no','s.student_name')->orderByDesc('point_buy.created_at')->paginate(30,['*'],'buy')->withQueryString();$sells=DB::table('point_sell')->leftJoin('bh_student as s','s.id','=','point_sell.student_id')->where('point_sell.user_id',$user)->select('point_sell.*','s.student_no','s.student_name')->orderByDesc('point_sell.created_at')->paginate(30,['*'],'sell')->withQueryString();return view('admin.pointbuysell.wallet',compact('u','buy','sell','buys','sells'));}
 private function summary(string $table,int $user){return DB::table($table)->where('user_id',$user)->selectRaw("COALESCE(SUM(CASE WHEN type=1 THEN point ELSE 0 END),0) credits, COALESCE(SUM(CASE WHEN type=2 THEN point ELSE 0 END),0) debits, COALESCE(SUM(CASE WHEN type=1 THEN point ELSE 0 END),0)-COALESCE(SUM(CASE WHEN type=2 THEN point ELSE 0 END),0) balance")->first();}
 public function convert(Request $r,int $user){$this->guard($r);$r->validate(['point'=>'required|integer|min:1']);DB::transaction(function()use($r,$user){$buy=$this->summary('point_buy',$user);abort_if($r->point>$buy->balance,422,'Buy balance is insufficient.');DB::table('point_buy')->insert(['user_id'=>$user,'student_id'=>0,'point'=>$r->point,'type'=>2,'created_at'=>now(),'reason'=>'Buy Point Convert Into Sell Point']);DB::table('point_sell')->insert(['user_id'=>$user,'student_id'=>0,'point'=>$r->point,'type'=>1,'created_at'=>now(),'reason'=>'Buy Point Convert Into Sell Point']);});return back()->with('success','Point converted successfully.');}
 public function status(Request $r,int $user){$this->guard($r);$r->validate(['buy_status'=>'required','sell_status'=>'required']);DB::table('bh_user_extra')->where('user_id',$user)->update(['buy_status'=>$r->buy_status,'sell_status'=>$r->sell_status]);return back()->with('success','Status updated.');}
 public function requests(Request $r){$this->guard($r);$q=DB::table('point_hold as h')->join('bh_student as s','s.id','=','h.student_id')->join('bh_user as u','u.user_id','=','h.user_id')->leftJoin('bh_user_extra as e','e.user_id','=','h.user_id')->select('h.*','s.student_no','s.student_name','e.user_no',DB::raw("TRIM(CONCAT(COALESCE(u.firstname,''),' ',COALESCE(u.lastname,''))) as user_name"))->when($r->filled('student_no'),fn($x)=>$x->where('s.student_no',$r->student_no))->when($r->filled('status'),fn($x)=>$x->where('h.status',$r->status))->orderByDesc('h.requested_at');$items=$q->paginate(30)->withQueryString();return view('admin.pointbuysell.requests',compact('items'));}
 public function accept(Request $r,int $id){$this->guard($r);DB::transaction(function()use($id){$h=DB::table('point_hold')->where('id',$id)->lockForUpdate()->first();abort_unless($h,404);abort_if($h->status==='Paid',422,'Already paid.');DB::table('point_hold')->where('id',$id)->update(['status'=>'Paid','approve_at'=>now()]);DB::table('point_buy')->insert(['user_id'=>$h->user_id,'student_id'=>$h->student_id,'point'=>$h->point,'created_at'=>now(),'type'=>1,'reason'=>'Accept by Pointbuysell ID']);});return back()->with('success','Buy request accepted.');}
 public function complain(Request $r,int $id){$this->guard($r);DB::table('point_hold')->where('id',$id)->update(['status'=>'Complain','complain_by_user'=>2]);return back()->with('success','Request marked as complain.');}
}