<?php
namespace AppHttpControllers;
use IlluminateHttpRequest;
use IlluminateSupportFacadesDB;
class AdminUserFinanceController extends Controller {
 private function guard(Request $r):void{abort_unless($r->session()->has('admin_user_id')&&(int)$r->session()->get('admin_user_group_id')===1,403);}
 private function users(){return DB::table('bh_user as u')->leftJoin('bh_user_extra as e','e.user_id','=','u.user_id')->leftJoin('bh_user_group as g','g.user_group_id','=','u.user_group_id')->select('u.user_id','u.firstname','u.lastname','u.username','e.user_no','g.name as user_group')->orderBy('u.user_id','desc');}
 public function passbook(Request $r){$this->guard($r);$q=DB::table('bh_user_passbook as p')->join('bh_user as u','u.user_id','=','p.user_id')->leftJoin('bh_user_extra as e','e.user_id','=','p.user_id')->select('p.*','u.firstname','u.lastname','e.user_no')->when($r->filled('user_no'),fn($x)=>$x->where('e.user_no',$r->user_no))->when($r->filled('type'),fn($x)=>$x->where('p.type',$r->type))->when($r->filled('reason'),fn($x)=>$x->where('p.reason','like','%'.$r->reason.'%'))->orderByDesc('p.created_at');$items=$q->paginate(40)->withQueryString();return view('admin.userfinance.passbook',compact('items'));}
 public function payments(Request $r){$this->guard($r);$q=DB::table('bh_user_payment_history as p')->join('bh_user as u','u.user_id','=','p.user_id')->leftJoin('bh_user_extra as e','e.user_id','=','p.user_id')->leftJoin('bh_user_withdrawal_request as w','w.id','=','p.withdrawal_request_id')->select('p.*','u.firstname','u.lastname','e.user_no','w.withdrawal_point')->when($r->filled('user_no'),fn($x)=>$x->where('e.user_no',$r->user_no))->when($r->filled('transaction_id'),fn($x)=>$x->where('p.transaction_id',$r->transaction_id))->orderByDesc('p.payment_date');$items=$q->paginate(40)->withQueryString();return view('admin.userfinance.payments',compact('items'));}
 public function withdrawals(Request $r){$this->guard($r);$q=DB::table('bh_user_withdrawal_request as w')->join('bh_user as u','u.user_id','=','w.user_id')->leftJoin('bh_user_extra as e','e.user_id','=','w.user_id')->select('w.*','u.firstname','u.lastname','e.user_no')->when($r->filled('user_no'),fn($x)=>$x->where('e.user_no',$r->user_no))->when($r->filled('status'),fn($x)=>$x->where('w.approve_status',$r->status))->orderByDesc('w.requested_at');$items=$q->paginate(40)->withQueryString();return view('admin.userfinance.withdrawals',compact('items'));}
 public function process(Request $r,int $id){$this->guard($r);$r->validate(['status'=>'required|in:Paid,Cancel','amount'=>'nullable|numeric|min:0']);DB::transaction(function()use($r,$id){$w=DB::table('bh_user_withdrawal_request')->where('id',$id)->lockForUpdate()->first();abort_unless($w,404);abort_if($w->approve_status!=='Pending',422,'Request already processed.');$data=['approve_status'=>$r->status,'admin_message'=>$r->input('comment'),'action_user_id'=>session('admin_user_id'),'approve_at'=>$r->status==='Paid'?now():null,'cancelled_at'=>$r->status==='Cancel'?now():null];DB::table('bh_user_withdrawal_request')->where('id',$id)->update($data);if($r->status==='Paid'){DB::table('bh_user_payment_history')->insert(['user_id'=>$w->user_id,'amount'=>$r->input('amount',0),'withdrawal_request_id'=>$id,'conversion_rate'=>$w->point_value,'payment_medium_id'=>$w->payment_medium,'transaction_id'=>$r->input('transaction_id'),'comment'=>$r->input('comment'),'screenshot_image'=>$r->input('screenshot_image'),'payment_date'=>now(),'created_by'=>session('admin_user_id')]);$last=DB::table('bh_user_passbook')->where('user_id',$w->user_id)->orderByDesc('id')->lockForUpdate()->first();$balance=$last?($last->balance_point-$w->withdrawal_point):-$w->withdrawal_point;abort_if($balance<0,422,'Insufficient user point balance.');DB::table('bh_user_passbook')->insert(['user_id'=>$w->user_id,'reason'=>'Amount transfer aganist '.$w->withdrawal_point,'description'=>$r->input('comment'),'credit_point'=>0,'debit_point'=>$w->withdrawal_point,'balance_point'=>$balance,'type'=>'Debit','created_at'=>now()]);}});return back()->with('success','Withdrawal processed.');}
}