<?php
namespace App\Http\Controllers;
use App\Models\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class StudentSellPointController extends Controller
{
 private function student(Request $r): Student { $id=$r->session()->get('student_id'); abort_unless($id,401); $s=Student::findOrFail($id); abort_unless((int)$s->student_status===1,403); return $s; }
 private function setting(string $key,$default=0){ return DB::table('bh_setting')->where('setting_key',$key)->value('setting_value') ?? $default; }
 private function balance($id){ return (float)(DB::table('bh_student_passbook')->where('student_id',$id)->orderByDesc('id')->value('balance_point') ?? 0); }
 private function point($id,$debit,$reason,$description){ $last=DB::table('bh_student_passbook')->where('student_id',$id)->orderByDesc('id')->first(); $bal=(float)($last->balance_point??0)-(float)$debit; DB::table('bh_student_passbook')->insert(['student_id'=>$id,'reason'=>$reason,'description'=>$description,'credit_point'=>0,'debit_point'=>$debit,'balance_point'=>$bal,'type'=>2,'created_at'=>now()]); DB::table('bh_student')->where('id',$id)->update(['student_point'=>$bal]); }
 public function index(Request $r){ $s=$this->student($r); $pending=(float)$this->setting('config_student_pending_point'); $min=(float)$this->setting('config_student_minimum_withdrawal_point'); $conv=(float)$this->setting('config_money_conversion'); $balance=$this->balance($s->id); $status=DB::table('bh_student_withdrawal_request')->where('student_id',$s->id)->where('approve_status','!=','Cancel')->exists()?1:0; $users=DB::table('bh_user as u')->join('bh_user_extra as ue','u.user_id','=','ue.user_id')->where('ue.buy_status',1)->where('u.user_group_id',17)->select('u.user_id','u.username','u.firstname','u.lastname')->get(); return view('student.sellpoint',compact('pending','min','conv','balance','status','users')); }
 public function addRequest(Request $r){ $s=$this->student($r); $data=$r->validate(['user_id'=>'required|integer','point'=>'required|numeric|min:1']); if(DB::table('bh_student_withdrawal_request')->where('student_id',$s->id)->where('approve_status','!=','Cancel')->exists()) return response()->json(['error'=>'Pending withdrawal point is not clear.'],422); $last=DB::table('point_hold')->where('student_id',$s->id)->orderByDesc('id')->first(); if($last && now()->diffInDays($last->requested_at)<=7) return response()->json(['error'=>'You can only send request once in a week.'],422); $balance=$this->balance($s->id); if($data['point']>$balance) return response()->json(['error'=>'Wrong withdrawal point request, please check balance point in your account.'],422); $min=(float)$this->setting('config_student_minimum_withdrawal_point'); if($data['point']<$min) return response()->json(['error'=>'Minimum withdrawal point condition not match.'],422); $conv=$this->setting('config_money_conversion'); DB::transaction(function()use($s,$data,$conv){ DB::table('point_hold')->insert(['student_id'=>$s->id,'user_id'=>$data['user_id'],'point'=>$data['point'],'requested_at'=>now(),'status'=>'Pending','point_value'=>$conv]); $this->point($s->id,$data['point'],'Sell Point Deduction','Sell request generated'); }); return response()->json(['success'=>'Sell Point request successfully send to Buyer ID.']); }
 public function list(Request $r){ $s=$this->student($r); $q=DB::table('point_hold as ph')->join('bh_user as u','ph.user_id','=','u.user_id')->where('ph.student_id',$s->id)->select('ph.*','u.username')->orderByDesc('ph.requested_at'); if($r->filled('filter_start_date'))$q->whereDate('ph.requested_at','>=',$r->input('filter_start_date')); if($r->filled('filter_end_date'))$q->whereDate('ph.requested_at','<=',$r->input('filter_end_date')); if($r->filled('filter_approve_status'))$q->where('ph.status',$r->input('filter_approve_status')); $rows=$q->paginate((int)$r->input('length',20)); return response()->json(['draw'=>(int)$r->input('draw',1),'recordsTotal'=>$rows->total(),'recordsFiltered'=>$rows->total(),'data'=>$rows->getCollection()->map(fn($x)=>['id'=>$x->id,'point'=>$x->point,'username'=>$x->username,'raw_status'=>$x->status,'is_transfer'=>$x->is_transfer,'screenshot'=>$x->screenshot?'<a href="'.e($x->screenshot).'" target="_blank">View</a>':'Not Added','requested_at'=>date('Y-m-d g:i A',strtotime($x->requested_at)),'approve_at'=>$x->approve_at?date('Y-m-d g:i A',strtotime($x->approve_at)):'N/A','cancelled_at'=>$x->cancelled_at?date('Y-m-d g:i A',strtotime($x->cancelled_at)):'N/A']])]); }
 public function complain(Request $r){ $s=$this->student($r); DB::table('point_hold')->where('id',$r->integer('id'))->where('student_id',$s->id)->update(['status'=>'Complain','complain_by_student'=>2]); return response()->json(['success'=>'Complain successfully added']); }
 public function accept(Request $r){ $s=$this->student($r); $id=$r->integer('id'); $hold=DB::table('point_hold')->where('id',$id)->where('student_id',$s->id)->first(); abort_unless($hold,404); DB::transaction(function()use($hold,$id){ DB::table('point_hold')->where('id',$id)->update(['is_transfer'=>2]); DB::table('point_buy')->insert(['user_id'=>$hold->user_id,'student_id'=>$hold->student_id,'point'=>$hold->point,'created_at'=>now(),'type'=>1,'reason'=>'Accepted by Student']); }); return response()->json(['success'=>'Thank you for accepting']); }
}