<?php
namespace App\Http\Controllers;
use App\Models\Student;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class StudentPointController extends Controller
{
 private function student(Request $r): Student { $id=$r->session()->get('student_id'); abort_unless($id,401); $s=Student::findOrFail($id); abort_unless((int)$s->student_status===1,403); return $s; }
 private function setting(string $key,$default=null){ $row=DB::table('bh_setting')->where('key',$key)->first(); if(!$row)return $default; if((int)($row->serialized??0)===1){$v=@unserialize($row->value); return $v===false&&$row->value!=='b:0;'?$default:$v;} return $row->value; }
 private function balance(int $id): float { return (float)(DB::table('bh_student_passbook')->where('student_id',$id)->orderByDesc('created_at')->orderByDesc('id')->value('balance_point')??0); }

 public function passbook(Request $r){$s=$this->student($r);$id=$s->id;return view('student.passbook',[
 'total_credit_point'=>(float)DB::table('bh_student_passbook')->where('student_id',$id)->where('type','Credit')->sum('credit_point'),
 'total_debit_point'=>(float)DB::table('bh_student_passbook')->where('student_id',$id)->where('type','Debit')->sum('debit_point'),
 'student_point'=>$this->balance($id),'total_amount'=>(float)DB::table('bh_student_payment_history')->where('student_id',$id)->sum('amount'),
 'total_request_withdrawal_point'=>(float)DB::table('bh_student_withdrawal_request')->where('student_id',$id)->where('approve_status','Pending')->sum('withdrawal_point'),
 'total_withdrawal_point'=>(float)DB::table('bh_student_withdrawal_request')->where('student_id',$id)->where('approve_status','Paid')->sum('withdrawal_point'),
 'filter_start_date'=>now()->startOfMonth()->toDateString(),'filter_end_date'=>now()->endOfMonth()->toDateString()]);}

 public function passbookList(Request $r){$s=$this->student($r);$q=DB::table('bh_student_passbook')->where('student_id',$s->id);if($r->filled('filter_start_date'))$q->whereDate('created_at','>=',$r->filter_start_date);if($r->filled('filter_end_date'))$q->whereDate('created_at','<=',$r->filter_end_date);if($r->filled('filter_type'))$q->where('type',$r->filter_type);$total=(clone$q)->count();$rows=$q->orderByDesc('created_at')->orderByDesc('id')->offset(max(0,(int)$r->input('start',0)))->limit(min(1000,max(1,(int)$r->input('length',20))))->get();return response()->json(['draw'=>(int)$r->input('draw',0),'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$rows->map(fn($x)=>['id'=>$x->id,'reason'=>$x->reason,'credit_point'=>$x->credit_point,'debit_point'=>$x->debit_point,'balance_point'=>$x->balance_point,'created_at'=>Carbon::parse($x->created_at)->format('Y-m-d g:i A'),'description'=>$x->description])->values()]);}

 public function withdrawal(Request $r){$s=$this->student($r);$id=$s->id;return view('student.withdrawal',[
 'student_pending_point'=>$this->setting('config_student_pending_point',0),'minimum_withdrawal_point'=>$this->setting('config_student_minimum_withdrawal_point',0),'money_conversion'=>$this->setting('config_money_conversion',0),
 'total_credit_point'=>DB::table('bh_student_passbook')->where('student_id',$id)->where('type','Credit')->sum('credit_point'),'total_debit_point'=>DB::table('bh_student_passbook')->where('student_id',$id)->where('type','Debit')->sum('debit_point'),'total_withdrawal_request_point'=>DB::table('bh_student_withdrawal_request')->where('student_id',$id)->where('approve_status','Pending')->sum('withdrawal_point'),'balance_point'=>$this->balance($id),
 'payment_medium'=>DB::table('bh_student_payment_medium')->where('student_id',$id)->get(),'status'=>DB::table('bh_student_withdrawal_request')->where('student_id',$id)->where('approve_status','!=','Cancel')->exists()?1:0,'filter_start_date'=>now()->startOfMonth()->toDateString(),'filter_end_date'=>now()->endOfMonth()->toDateString()]);}

 public function withdrawalList(Request $r){$s=$this->student($r);$q=DB::table('bh_student_withdrawal_request')->where('student_id',$s->id);if($r->filled('filter_approve_status'))$q->where('approve_status',$r->filter_approve_status);if($r->filled('filter_start_date'))$q->whereDate('requested_at','>=',$r->filter_start_date);if($r->filled('filter_end_date'))$q->whereDate('requested_at','<=',$r->filter_end_date);$total=(clone$q)->count();$rows=$q->orderByDesc('requested_at')->orderByDesc('id')->offset(max(0,(int)$r->input('start',0)))->limit(min(1000,max(1,(int)$r->input('length',20))))->get();return response()->json(['draw'=>(int)$r->input('draw',0),'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$rows->map(fn($x)=>['id'=>$x->id,'withdrawal_point'=>$x->withdrawal_point,'requested_at'=>$x->requested_at?Carbon::parse($x->requested_at)->format('Y-m-d g:i A'):'N/A','approve_status'=>$x->approve_status,'approve_at'=>$x->approve_at&&$x->approve_at!=='0000-00-00 00:00:00'?Carbon::parse($x->approve_at)->format('Y-m-d g:i A'):'N/A','cancelled_at'=>$x->cancelled_at&&$x->cancelled_at!=='0000-00-00 00:00:00'?Carbon::parse($x->cancelled_at)->format('Y-m-d g:i A'):'N/A','comment'=>$x->withdrawal_message])->values()]);}

 public function addWithdrawal(Request $r){$s=$this->student($r);$d=$r->validate(['withdrawal_point'=>['required','numeric','gt:0'],'payment_medium'=>['required','string','max:255'],'withdrawal_message'=>['nullable','string','max:1000']]);$out=DB::transaction(function()use($s,$d){$sr=Student::whereKey($s->id)->lockForUpdate()->firstOrFail();$pending=(float)$this->setting('config_student_pending_point',0);$minimum=(float)$this->setting('config_student_minimum_withdrawal_point',0);$conversion=$this->setting('config_money_conversion',0);if(DB::table('bh_student_withdrawal_request')->where('student_id',$sr->id)->where('approve_status','!=','Cancel')->exists())return['error'=>'You already have a pending withdrawal request.'];$last=DB::table('bh_student_withdrawal_request')->where('student_id',$sr->id)->where('type',1)->orderByDesc('id')->first();if($last){$dt=$last->approve_status==='Pending'?$last->requested_at:($last->approve_status==='Paid'?$last->approve_at:$last->cancelled_at);if($dt&&Carbon::parse($dt)->startOfDay()->diffInDays(now()->startOfDay())<=7)return['error'=>'You can only send request once in a week.'];}$balance=$this->balance($sr->id);$requested=(float)$d['withdrawal_point'];if($requested>$balance)return['error'=>'Wrong withdrawal point request, please check balance point in your account.'];if($pending>0&&DB::table('bh_student_withdrawal_request')->where('student_id',$sr->id)->where('approve_status','!=','Cancel')->doesntExist()){if($requested<$pending)return['error'=>'Pending withdrawal point condition not match.'];if($pending>$balance)return['error'=>'Pending withdrawal point is greater than your available balance.'];$new=$balance-$pending;DB::table('bh_student_passbook')->insert(['student_id'=>$sr->id,'reason'=>'Pending Point Deduction','description'=>'Automatically deduction of pending point by system','credit_point'=>0,'debit_point'=>$pending,'balance_point'=>$new,'type'=>'Debit','created_at'=>now()]);$sr->student_point=$new;$sr->save();DB::table('bh_student_withdrawal_request')->insert(['student_id'=>$sr->id,'withdrawal_point'=>$pending,'requested_at'=>now(),'approve_at'=>now(),'approve_status'=>'Paid','payment_medium'=>$d['payment_medium'],'withdrawal_message'=>'Pending Fees','point_value'=>$conversion,'type'=>2]);return['success'=>'Pending point successfully cleared and recorded as paid.'];}if($requested<$minimum)return['error'=>'Minimum withdrawal point condition not match.'];DB::table('bh_student_withdrawal_request')->insert(['student_id'=>$sr->id,'withdrawal_point'=>$requested,'requested_at'=>now(),'approve_status'=>'Pending','payment_medium'=>$d['payment_medium'],'withdrawal_message'=>$d['withdrawal_message']??null,'point_value'=>$conversion,'type'=>1]);return['success'=>'Withdrawal request successfully sent to admin.'];});return response()->json($out,isset($out['error'])?422:200);}

 public function joinRequest(Request $r){$s=$this->student($r);DB::table('bh_student')->where('id',$s->id)->where('admin_approve',1)->update(['is_point_requested'=>1]);return response()->json(['success'=>true]);}
}