@extends('layouts.admin')

@section('title', 'Students')

@section('content')
<div class="panel"><div style="display:flex;justify-content:space-between;gap:15px;flex-wrap:wrap"><div><h1>{{ $status===0 ? 'Pending Students' : ($status===2 ? 'Blocked Students' : 'Active Students') }}</h1><p class="muted">Student management</p></div><a class="btn" href="{{ route('admin.dashboard') }}">Dashboard</a></div>
@if(session('success'))<div class="alert" style="background:#dcfce7;color:#166534">{{ session('success') }}</div>@endif
<form method="GET" class="grid"><input name="search" placeholder="Name, ID, phone, WhatsApp, email, language" value="{{request('search')}}"><input name="student_no" placeholder="Student ID" value="{{request('student_no')}}"><input name="refer_no" placeholder="Refer ID" value="{{request('refer_no')}}"><select name="status"><option value="1" @selected($status===1)>Active</option><option value="0" @selected($status===0)>Pending</option><option value="2" @selected($status===2)>Blocked</option></select><button class="btn" type="submit">Search</button></form></div>
<div class="table-wrap"><table class="table"><thead><tr><th>No</th><th>Name</th><th>WhatsApp</th><th>Point</th><th>Refer By</th><th>Trainer</th><th>Activated</th><th>Join</th><th>Counsellor</th><th>Point</th><th>Action</th></tr></thead><tbody>
@forelse($students as $s)<tr><td>{{$s->student_no}}</td><td>{{$s->student_name}}</td><td>{{$s->student_whatsapp}}</td><td>{{$s->student_point}}</td><td>{{trim(($s->refer_name??'').' '.($s->refer_no?'('.$s->refer_no.')':''))}}</td><td>{{trim(($s->trainer_firstname??'').' '.($s->trainer_lastname??'').' '.($s->trainer_no?'('.$s->trainer_no.')':''))}}</td><td>{{$s->activated_at}}</td>
<td>@if((int)$s->whatsapp_join===1 && (int)$s->telegram_join===1 && (int)$s->admin_approve===0)<form method="POST" action="{{route('admin.students.join-approve',$s->id)}}">@csrf<button class="btn" type="submit">Approve Join</button></form>@elseif((int)$s->admin_approve===1 && (int)$s->is_point_requested===1 && (int)$s->is_point_send===0)<form method="POST" action="{{route('admin.students.join-send',$s->id)}}">@csrf<button class="btn" type="submit">Send Point</button></form>@else<span class="muted">—</span>@endif</td>
<td><form method="POST" action="{{route('admin.students.assign-counsellor',$s->id)}}">@csrf<select name="counsellor_id"><option value="">Counsellor</option>@foreach($counsellors as $c)<option value="{{$c->user_id}}">{{$c->firstname}} {{$c->lastname}} ({{$c->user_no}})</option>@endforeach</select><button class="btn" type="submit">Assign</button></form></td>
<td><form method="POST" action="{{route('admin.students.add-point',$s->id)}}">@csrf<input name="point" type="number" step="0.01" min="0.01" placeholder="Point" required><input name="reason" placeholder="Reason" required><button class="btn" type="submit">Add</button></form><form method="POST" action="{{route('admin.students.remove-point',$s->id)}}" style="margin-top:4px">@csrf<input name="point" type="number" step="0.01" min="0.01" placeholder="Point" required><input name="reason" placeholder="Reason" required><button class="btn btn-secondary" type="submit">Deduct</button></form></td>
<td><div style="display:flex;gap:5px;flex-wrap:wrap">@if($status===0)<form method="POST" action="{{route('admin.students.activate',$s->id)}}" onsubmit="return confirm('Activate this student?')">@csrf<button class="btn" type="submit">Activate</button></form>@endif<a class="btn" href="{{route('admin.students.edit',$s->id)}}">Edit</a><a class="btn btn-secondary" href="{{route('admin.students.referrals',$s->id)}}">Referrals</a>@if($status===2)<form method="POST" action="{{route('admin.students.unblock',$s->id)}}">@csrf<button class="btn" type="submit">Unblock</button></form>@else<form method="POST" action="{{route('admin.students.block',$s->id)}}" onsubmit="return confirm('Block this student?')">@csrf<button class="btn btn-secondary" type="submit">Block</button></form>@endif</div></td></tr>
@empty<tr><td colspan="11">No students found.</td></tr>@endforelse</tbody></table></div>{{$students->links()}}
@endsection
