<?php echo $header; ?><?php echo $column_left; ?><div id="content"><div class="container-fluid">
<div class="page-header"><h1><i class="fa fa-clock-o"></i> Counsellor Attendance</h1></div>
<div class="panel panel-default"><div class="panel-heading"><strong>Meeting Time</strong><?php if($is_super_admin){ ?><div class="pull-right"><button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#time-modal"><i class="fa fa-plus"></i> Add Time</button></div><?php } ?></div><div class="panel-body">
<?php if($is_admin){ ?><select class="form-control" style="max-width:300px" onchange="location.href='<?php echo $reload; ?>&meeting_time_id='+this.value"><?php foreach($times as $time){ ?><option value="<?php echo $time['id']; ?>" <?php echo $selected_id==(int)$time['id']?'selected':''; ?>><?php echo date('g:i A',strtotime($time['meeting_time'])); ?></option><?php } ?></select><p class="help-block">Admin can mark attendance for any configured meeting time.</p>
<?php } elseif($current_slot){ ?><div class="alert alert-info">Active meeting: <strong><?php echo date('g:i A',strtotime($current_slot['meeting_time'])); ?></strong>. Attendance window is open for 60 minutes.</div>
<?php } else { ?><div class="alert alert-warning">No meeting is currently open. Attendance opens for 60 minutes after each configured meeting time.</div><?php } ?></div></div>
<?php if($selected_id){ ?><form method="post" action="<?php echo $action; ?>"><input type="hidden" name="meeting_time_id" value="<?php echo $selected_id; ?>"><div class="panel panel-default"><div class="panel-heading"><strong>Counsellor List — <?php echo date('d M Y',strtotime($date)); ?></strong><div class="pull-right"><?php if($is_admin||$current_slot){ ?><button type="submit" class="btn btn-success btn-xs"><i class="fa fa-check"></i> Send Attendance</button><?php } ?></div></div><div class="panel-body"><div class="table-responsive"><table class="table table-striped table-bordered"><thead><tr><th>#</th><th>Counsellor ID</th><th>Name</th><th>Status</th><th>Attendance</th></tr></thead><tbody>
<?php $i=1; foreach($counsellors as $c){ $marked=isset($attendance[(int)$c['user_id']]); ?><tr><td><?php echo $i++; ?></td><td><?php echo $c['user_no']; ?></td><td><?php echo htmlspecialchars($c['firstname'].' '.$c['lastname']); ?></td><td><?php echo (int)$c['status']===1?'Enabled':'Disabled'; ?></td><td><?php if($marked){ ?><span class="label label-success"><i class="fa fa-check"></i> Present</span> <small><?php echo date('g:i A',strtotime($attendance[(int)$c['user_id']]['marked_at'])); ?></small><?php } elseif($is_admin||$current_slot){ ?><label style="font-weight:normal"><input type="checkbox" name="counsellor[]" value="<?php echo $c['user_id']; ?>"> Send Attendance</label><?php } else { ?><span class="label label-default">Closed</span><?php } ?></td></tr><?php } ?>
</tbody></table></div></div></div></form><?php } ?>
<?php if($is_super_admin){ ?><div class="panel panel-info"><div class="panel-heading"><strong>Super Admin — Meeting Time Settings</strong></div><div class="panel-body"><p>Add as many meeting times as needed. Every configured time opens a 60-minute controller attendance window.</p><table class="table table-bordered"><thead><tr><th>Time</th><th>Action</th></tr></thead><tbody><?php foreach($times as $time){ ?><tr><td><?php echo date('g:i A',strtotime($time['meeting_time'])); ?></td><td><button type="button" class="btn btn-danger btn-xs delete-time" data-id="<?php echo $time['id']; ?>"><i class="fa fa-trash"></i></button></td></tr><?php } ?></tbody></table></div></div><?php } ?>
</div></div>
<?php if($is_super_admin){ ?><div class="modal fade" id="time-modal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form id="time-form"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4>Add Meeting Time</h4></div><div class="modal-body"><input type="time" name="meeting_time" class="form-control" required></div><div class="modal-footer"><button type="submit" class="btn btn-primary">Add Time</button></div></form></div></div></div><script>
$('#time-form').on('submit',function(e){e.preventDefault();$.post('<?php echo $add_time; ?>',$(this).serialize(),function(j){if(j.success)location.reload();else alert(j.error||'Unable to add time.');},'json');});
$('.delete-time').on('click',function(){if(!confirm('Delete this meeting time?'))return;$.post('<?php echo $delete_time; ?>',{id:$(this).data('id')},function(j){if(j.success)location.reload();else alert(j.error||'Unable to delete time.');},'json');});
</script><?php } ?><?php echo $footer; ?>
