<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
class AdminUserProfileController extends Controller {
 private function guard(Request $r):void{abort_unless($r->session()->has('admin_user_id'),403);}
 public function edit(Request $r){$this->guard($r);$id=(int)$r->session()->get('admin_user_id');$user=DB::table('bh_user as u')->leftJoin('bh_user_extra as e','e.user_id','=','u.user_id')->where('u.user_id',$id)->select('u.*','e.phone','e.whatsapp','e.gender','e.city','e.country','e.language','e.user_no')->first();abort_unless($user,404);$mediums=DB::table('bh_user_payment_medium')->where('user_id',$id)->get();return view('admin.user-profile',compact('user','mediums'));}
 public function update(Request $r){$this->guard($r);$id=(int)$r->session()->get('admin_user_id');$d=$r->validate(['firstname'=>['required','string','min:1','max:32'],'lastname'=>['required','string','min:1','max:32'],'email'=>['nullable','email','max:150'],'phone'=>['required','string','max:32'],'whatsapp'=>['required','string','max:32'],'gender'=>['nullable','string','max:20'],'city'=>['nullable','string','max:100'],'country'=>['nullable','string','max:80'],'language'=>['nullable','string','max:50'],'password'=>['nullable','string','min:8','confirmed']]);DB::transaction(function()use($id,$d){DB::table('bh_user')->where('user_id',$id)->update(['firstname'=>$d['firstname'],'lastname'=>$d['lastname'],'email'=>$d['email']??'']);DB::table('bh_user_extra')->where('user_id',$id)->update(['phone'=>$d['phone'],'whatsapp'=>$d['whatsapp'],'gender'=>$d['gender']??'','city'=>$d['city']??'','country'=>$d['country']??'','language'=>$d['language']??'']);if(!empty($d['password']))DB::table('bh_user')->where('user_id',$id)->update(['password'=>Hash::make($d['password'])]);if(request()->has('payment_medium')){DB::table('bh_user_payment_medium')->where('user_id',$id)->delete();foreach((array)request()->input('payment_medium',[]) as $m){if(trim($m['medium_name']??'')!==''&&trim($m['medium_code']??'')!=='')DB::table('bh_user_payment_medium')->insert(['user_id'=>$id,'medium_name'=>$m['medium_name'],'medium_code'=>$m['medium_code'],'medium_status'=>(int)($m['medium_status']??0)]);}}});return back()->with('success','Profile updated successfully.');}
}