@extends('layouts.admin')

@section('title', 'wallet')

@push('head')
<style>body{font-family:Arial;background:#f5f7fb;margin:0;color:#1f2937}.wrap{max-width:1200px;margin:auto;padding:25px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:18px;margin-top:18px}input,select{padding:9px;border:1px solid #d0d5dd;border-radius:7px}button,.btn{padding:8px 11px;border:0;border-radius:7px;background:#2563eb;color:#fff;text-decoration:none}table{width:100%;border-collapse:collapse;margin-top:15px}th,td{padding:9px;border-bottom:1px solid #eee;text-align:left}.ok{padding:10px;background:#e7f7ed}</style>
@endpush

@section('content')
<div class="wrap"><a href="{{route('admin.dashboard')}}">Dashboard</a> | <a href="{{route('admin.pointbuysell.index')}}">Point Buy/Sell</a> | <a href="{{route('admin.pointbuysell.requests')}}">Buy Requests</a><h1>Wallet: {{$u->firstname}} {{$u->lastname}}</h1>@if(session('success'))<div class="ok">{{session('success')}}</div>@endif<div class="card"><strong>Buy Balance:</strong> {{$buy->balance}} &nbsp; <strong>Sell Balance:</strong> {{$sell->balance}}<form method="post" action="{{route('admin.pointbuysell.convert',$u->user_id)}}" style="margin-top:12px">@csrf <input type="number" name="point" min="1" placeholder="Convert buy → sell"><button>Convert</button></form><form method="post" action="{{route('admin.pointbuysell.status',$u->user_id)}}" style="margin-top:12px">@csrf <select name="buy_status"><option value="1" @selected($u->buy_status==1)>Buy On</option><option value="0" @selected($u->buy_status==0)>Buy Off</option></select><select name="sell_status"><option value="1" @selected($u->sell_status==1)>Sell On</option><option value="0" @selected($u->sell_status==0)>Sell Off</option></select><button>Save Status</button></form></div><div class="card"><h3>Buy History</h3><table><tr><th>Date</th><th>Type</th><th>Point</th><th>Student</th><th>Reason</th></tr>@foreach($buys as $x)<tr><td>{{$x->created_at}}</td><td>{{$x->type==1?'Credit':'Debit'}}</td><td>{{$x->point}}</td><td>{{$x->student_name}} {{$x->student_no}}</td><td>{{$x->reason}}</td></tr>@endforeach</table>{{$buys->links()}}</div><div class="card"><h3>Sell History</h3><table><tr><th>Date</th><th>Type</th><th>Point</th><th>Student</th><th>Reason</th></tr>@foreach($sells as $x)<tr><td>{{$x->created_at}}</td><td>{{$x->type==1?'Credit':'Debit'}}</td><td>{{$x->point}}</td><td>{{$x->student_name}} {{$x->student_no}}</td><td>{{$x->reason}}</td></tr>@endforeach</table>{{$sells->links()}}</div></div>
@endsection
